# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  ldflags: -s -X github.com/sunny0826/hamal/cmd.hamalVersion={{.Version}} -X github.com/sunny0826/hamal/cmd.gitCommit={{.Commit}} -X github.com/sunny0826/hamal/cmd.buildDate={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-rc"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
